spring:
  profiles:
    active: local
---
server:
  port: 8080
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: pass
    hikari:
      max-lifetime: 25000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
#    host: ruid-test.v3rhpd.0001.apn2.cache.amazonaws.com
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: always
  http:
    log-request-details: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  jackson:
    serialization:
      fail-on-empty-beans: false

#    org.hibernate:
#      SQL: DEBUG
#      type:
#        descriptor:
#          sql: trace #hibernate 바인드 파라미터 정보 표현 설정