spring:
  profiles:
    active: local
---
server:
  port: 8080
spring:
  profiles: local
  output:
    ansi:
      enabled: always
  http:
    log-request-details: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  jackson:
    serialization:
      fail-on-empty-beans: false